### ISSUE TITLE
Support for single-currency org

### ISSUE THREAD

**Issue by Daankrn** [ministe2003/cloneOppWithProducts#1]
It would be great to have a version of this app for single-currency organizations.

Currently it won't install on my org as we have no multi-currency support enabled.

It would require mentions of CurrencyIsoCode and apexType currency to be removed from the Controller classes.

**Comment by Swizzle4372** [comment]
Good suggestion.  I've updated the test class to remove the CurrencyIsoCode field reference.  The ApexType currency references can remain without making multi-currency required.
I've updated the link in the readme so you can download the new version

**Comment by Daankrn** [comment]
Thanks! I'll try to implement somewhere today!
